core/urls.py
from django.urls import path, include, re_path

from core.views import change_password

app_name = 'core'

urlpatterns = [
    path('accounts/change-password/', change_password,
         name='account_change_password'),

]

ictobservatory/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings

from django.conf.urls.static import static
import notifications.urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("select2/", include("django_select2.urls")),
    re_path(
        "^inbox/notifications/", include(notifications.urls,
                                         namespace="notifications")
    ),
    path("", include("portal.urls")),
    path("portaldata/", include("portaldata.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("core.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# settings.MEDIA_URL, document_root=settings.MEDIA_ROOT changed during deployment

portal/urls.py
from django.urls import path

from portal.views.map_views import map_view
from .views.portal_home_views import index, socio_economic, about
from .views.querydata_views import generate_report

app_name = 'portal'

urlpatterns = [
    #'''Home Page'''
    path('', index, name='index'),

    #'''Socio Economic Charts page'''
    path('socio-economic/', socio_economic, name='socio-economic-charts'),


    #'''Query Data page'''
    path('query-data/', generate_report, name='generate-report'),


    #'''About Page'''
    path('about/', about, name='about'),


    path('map/', map_view, name='map'),



]

portaldata/urls.py
from django.urls import path

from portaldata.views.profile_views import view_profile
from .views.home_views import documentation, index, send_message_by_admins, send_message_by_ms
from .views.admin_views import (
    GeneralIndicatorCreateView,
    GeneralIndicatorListView,
    GeneralIndicatorUpdateView,
    IndicatorCreateView,
    IndicatorListtableView,
    IndicatorUpdateView,
    FocusAreaListView,
    FocusAreaCreateView,
    FocusAreaUpdateView,
    ReportingPeriodCreateView,
    ReportingPeriodListView,
    ReportingPeriodUpdateView,
    indicator_list_view,
    manage_indicatorassignment,
    publish_data,
)

from .views.indicator_data_views import (
    ViewIndicatorDatatableView,
    data_entry_progress_by_ms,
    manage_general_indicatordata,
    manage_indicatordata,
    manage_indicatordata_organisation,
    show_indicator_definition,
    submit_indicator_data_by_ms,
    data_entry_progress_by_org,
    submit_indicator_data_by_org,
    view_indicatordata,
)

from .views.exchangerate_data_views import exchange_rate_data

from .views.indicator_data_validation import (
    IndicatorDatatableView,
    indicatordata_list_view,
    validate_data,
    send_back_for_revision,
)


app_name = "portaldata"

urlpatterns = [
    path("", index, name="index"),
    path("create-indicator/", IndicatorCreateView.as_view(), name="createindicator"),
    #'''Page to show the list of indicators to be validated'''
    path("manage-indicators/", indicator_list_view, name="manageindicators"),
    #''' Ajax page to feed data to the page described above'''
    path(
        "manage-indicator-ajax/",
        IndicatorListtableView.as_view(),
        name="manage-indicator-ajax",
    ),
    path(
        "update-indicator/<int:pk>/",
        IndicatorUpdateView.as_view(),
        name="updateindicator",
    ),
    path("manage-focus-area/", FocusAreaListView.as_view(), name="managefocusarea"),
    path("create-focus-area/", FocusAreaCreateView.as_view(), name="createfocusarea"),
    path(
        "update-focus-area/<int:pk>/",
        FocusAreaUpdateView.as_view(),
        name="updatefocusarea",
    ),
    path(
        "manage-reporting-period/",
        ReportingPeriodListView.as_view(),
        name="managereportingperiod",
    ),
    path(
        "create-reporting-period/",
        ReportingPeriodCreateView.as_view(),
        name="createreportingperiod",
    ),
    path(
        "update-reporting-period/<int:pk>/",
        ReportingPeriodUpdateView.as_view(),
        name="updatereportingperiod",
    ),
    path(
        "indicator-assignment/", manage_indicatorassignment, name="indicator-assignment"
    ),
    path(
        "manage-general-indicator/",
        GeneralIndicatorListView.as_view(),
        name="managegeneralindicators",
    ),
    path(
        "create-general-indicator/",
        GeneralIndicatorCreateView.as_view(),
        name="creategeneralindicator",
    ),
    path(
        "update-general-indicator/<int:pk>/",
        GeneralIndicatorUpdateView.as_view(),
        name="updategeneralindicator",
    ),
    # '''Data Entry Progress Page URL for Member States'''
    path("data-entry-by-ms/", data_entry_progress_by_ms, name="dataentrybyms"),
    # '''Data Entry Progress for Organisations'''
    path("data-entry-by-org/", data_entry_progress_by_org, name="dataentrybyorg"),
    # Data Entry Page for SADC - For General Indicators
    path(
        "manage-general-indicator-data/",
        manage_general_indicatordata,
        name="dataentrybysadc",
    ),
    # '''Data Entry Page for Member States - For a selected Focus Area'''
    path(
        "manage-indicator-data/<int:id>/",
        manage_indicatordata,
        name="manage_indicatordata",
    ),
    # '''Data Entry Page for Organizations - for a selected indicator'''
    path(
        "manage-indicator-data-org/<int:id>/",
        manage_indicatordata_organisation,
        name="manage_indicatordata_organisation",
    ),
    # '''Page to show the list of indicators data completed by Member States'''
    path(
        "view-indicator-data/",
        view_indicatordata,
        name="view-indicator-data",
    ),
    # '''Ajax page to feed data to the page described above'''
    path(
        "view-indicator-data-ajax/",
        ViewIndicatorDatatableView.as_view(),
        name="view-indicator-data-ajax",
    ),
    # '''Exchange data entry page for Member States'''
    path("dataentrybyms/exchange-rate", exchange_rate_data, name="exchange-rate"),
    path("show-definition/<int:id>/",
         show_indicator_definition, name="showdefinition"),
    # '''Indicator Submit Page (for Submit button) for Member States'''
    path("submit-indicator-data/", submit_indicator_data_by_ms,
         name="submitIndicatorData"),
    # '''Indicator Submit Page for Organizations'''
    path(
        "submit-indicator-data-by-org/",
        submit_indicator_data_by_org,
        name="submitIndicatorDatabyOrg",
    ),
    # '''Start indicator Validation'''
    # '''Page to show the list of indicators to be validated'''
    path(
        "validate-indicator-data/",
        indicatordata_list_view,
        name="validate-indicator-data",
    ),
    # '''Ajax page to feed data to the page described above'''
    path(
        "manage-indicator-data-ajax/",
        IndicatorDatatableView.as_view(),
        name="manage-indicator-data-ajax",
    ),
    # '''Validate data button'''
    path("validate-data/", validate_data, name="validate-data"),
    # '''Send back to revision button'''
    path("sendback/<int:id>/", send_back_for_revision, name="sendback"),
    # '''End indicator validation'''
    # '''Profile'''
    path("manage-profile/", view_profile, name="profile"),
    # '''Documentation'''
    path("documentation/", documentation, name="documentation"),
    # '''Send Message for Admins'''
    path("send-message-admin/", send_message_by_admins, name="send-message-admin"),
    # '''Send Message for Member States'''
    path("send-message-ms/", send_message_by_ms, name="send-message-ms"),
    # '''Publish'''
    path("publish-data/", publish_data, name="publish-data"),
]

templates/partials/_auth_navbar.html
{% load static %}
{% load notifications_tags %}
<script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
{% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}


 <!--begin::Header navbar name, profile picture, preferences and logout-->
 <nav class="navbar header-nav navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">


    
    <div class="container-fluid">
        
     
    {% if user.is_authenticated %}   
    
    {% notifications_unread as unread_count %}

    

   
      <button class="btn btn-link  rounded-circle me-3" id="sidebarToggleTop"
       type="button"><i class="fas fa-bars"></i>
      </button>
      
      
        <ul class="navbar-nav flex-nowrap ms-auto">
            
            
            <li class="nav-item dropdown no-arrow mx-1">
                <div class="nav-item dropdown no-arrow">
                    
                    <a class="dropdown-toggle nav-link nav-icon"
                        aria-expanded="false" data-bs-toggle="dropdown" href="#">

                        
                        <span class="badge bg-primary  badge-counter sme">{% live_notify_badge  %}</span>
                        
                        
                            <i class="fas fa-bell fa-fw"></i></a>
                    <div class="dropdown-menu dropdown-menu-end dropdown-list animated--grow-in">
                        <h6 class="dropdown-header inline-block">
                            <a class="text-white text-decoration-none" href="{% url 'notifications:all' %}">
                        Notifications center </a>
                        <a class=" float-end" 
                        href="{% url 'notifications:mark_all_as_read' %}?next={{ request.get_full_path }}">
                        <span class="bi bi-envelope-open text-white" 
                        data-toggle="tooltip" title="Mark all as read."></span>
                        
                    </a></h6>
                   

                        {% if user.notifications.unread %}


                        {% for notification in  user.notifications.unread %}
                       

                        <a class="dropdown-item d-flex align-items-center" href="{% url 'notifications:mark_as_read' notification.slug %}?next={{ request.get_full_path }}" >
                            <div class="me-3">
                                <i class="bi bi-info-circle-fill" style="color:blue;"></i>
                            </div>
                            <div><span class="small text-gray-500">{{ notification.timestamp }} </span><br>
                                <strong>From:</strong> {{ notification.actor|title }}
                                <br><strong>Subject:</strong> {{ notification.verb }} <br>
                                {% if notification.description %}
                                <p>{{ notification.description }}</p>{% endif %}
                            </div>
                           
                        </a>
                        {% endfor %}
                        {% else %}
                        <div class="dropdown-item d-flex align-items-center">
                        <div class="me-3 ">
                            <i class="bi bi-info-circle-fill" style="color:blue;"></i>
                        </div>
                        <div><span class="small text-gray-500">No Unread Notifications </span></div>
                        
                    </div>
                        
                        

                        {% endif %}
                        <a class="dropdown-item text-center small text-gray-500" href="{% url 'notifications:all' %}">
                            Show All
                            Notifications</a>
                        
                       
                        
                        
                        
                        {% comment %} <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="me-3">
                                <div class="bg-warning icon-circle"><i
                                        class="fas fa-exclamation-triangle text-white"></i></div>
                            </div>
                            <div><span class="small text-gray-500">December 2, 2019</span>
                                <p>Spending Alert: We've noticed unusually high spending for your
                                    account.</p>
                            </div>
                        </a> {% endcomment %}
                        
                        
                    </div>
                </div>
            </li>
            
            <div class="d-none d-sm-block topbar-divider"></div>
            
            <li class="nav-item dropdown no-arrow">
                <div class="nav-item dropdown no-arrow"><a class="dropdown-toggle nav-link"
                        aria-expanded="false" data-bs-toggle="dropdown" href="#"><span
                            class="d-none d-lg-inline me-2 text-gray-600 small">{{ user.get_full_name|title }}</span><img
                            class="border rounded-circle img-profile"
                            src="{% static 'img/avatars/avatardefault.png' %}"></a>
                    <div class="dropdown-menu shadow dropdown-menu-end animated--grow-in"><a
                            class="dropdown-item" href="{% url 'portaldata:profile' %}"><i
                                class="fas fa-user fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Profile</a>
                                
                        <div class="dropdown-divider"></div><a class="dropdown-item" href="{% url 'logout' %}"><i
                                class="fas fa-sign-out-alt fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Logout</a>
                    </div>
                </div>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>

<!--end::Header navbar name, profile picture, preferences and logout-->

templates/partials/_messages.html
{% load static %}
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div{% if message.tags %} class="alert alert-dismissible alert-{{ message.tags }}" role="alert" {% endif %}>
        
        {{ message }}

        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</ul>
</div>
{% endif %}

<script>
    $(document).ready(function(){
        window.setTimeout(function() {
            $(".alert").fadeTo(500, 0).slideUp(500, function(){
            $(this).remove();
            });
        }, 10000);
    });
</script>

templates/partials/_sidebar.html
{% load static %}
{% load dataentrytags %}
{% load notifications_tags %}
<script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
{% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}



<nav  class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0      ">
            <div class="container-fluid d-flex  p-0   " > <!--flex-column-->
              <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0 " href="{% url 'portal:index' %}">
                    <div class="logo " >
                      <img src="{% static 'img/sadc-logo-circle.svg' %}  " alt="logo">
                      
                    </div>
                    
              </a>
             
              
                <hr class="sidebar-divider my-0">
                {% with request.resolver_match.url_name as url_name %}
                <ul class="navbar-nav text-light mt-2   " id="accordionSidebar">

                    <li class="nav-item"><a class="nav-link {% if url_name == 'index' %}active{% endif %}" href=" {% url 'portaldata:index' %}">
                      <i class="fas fa-home"></i><span> Home</span></a>
                    </li>

                    
                    {% comment %} <li class="nav-item"><a class="nav-link active" href=" {% url 'portaldata:manageindicators' %}">
                      <i class="fas fa-tachometer-alt"></i><span>Manage Indicators</span></a>
                    </li> {% endcomment %}
                    {% if user.is_authenticated %}

                    {% if user.is_sadc or user.is_superuser %}  

                    <li class="nav-heading"></li>

                    

                    

    <!--Start collapse Menu-->
      <!--
                    <li class="nav-item">
                      <a class="nav-link  align-items-center" style="cursor:pointer;" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true">
                        <i class="bi bi-menu-button-wide"></i><span> Manage </span>
                        
                      </a>
                      <div class="collapse " id="home-collapse" style="">
                        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                          <li class="nav-item">
                            <a class="nav-link {% if url_name == 'managereportingperiod' %}active{% endif %}" href=" {% url 'portaldata:managereportingperiod' %}">
                            <i class="bi bi-menu-button-wide"></i><span> Reporting Periods</span></a>
                          </li>

                          <li class="nav-item"><a class="nav-link {% if url_name == 'managefocusarea' %}active{% endif %}" href=" {% url 'portaldata:managefocusarea' %}">
                            <i class="bi bi-menu-button-wide"></i><span> Focus Areas</span></a>
                          </li>
                      
                          <li class="nav-item"><a class="nav-link {% if url_name == 'manageindicators' %}active{% endif %}" href=" {% url 'portaldata:manageindicators' %}">
                            <i class="bi bi-menu-button-wide"></i><span> Indicators</span></a>
                          </li>
                          <li class="nav-item"><a class="nav-link {% if url_name == 'indicator-assignment' %}active{% endif %}" href=" {% url 'portaldata:indicator-assignment' %}">
                            <i class="bi bi-menu-button-wide"></i><span> Indicators</span></a>
                          </li>
                          
                          <li class="nav-item"><a class="nav-link {% if url_name == 'managegeneralindicators' %}active{% endif %}" href=" {% url 'portaldata:managegeneralindicators' %}">
                            <i class="bi bi-menu-button-wide"></i><span> General Indicators</span></a>
                          </li>
                         

                        </ul>
                      </div>
                    </li>

                     -->

            <!--End collapse Menu-->

                  
                

                  

                   

             <!--Start Manage Menu-->

           

                    <li class="nav-item">
                      <a class="nav-link {% if url_name == 'managereportingperiod' %}active{% endif %}" href=" {% url 'portaldata:managereportingperiod' %}">
                      <i class="bi bi-menu-button-wide"></i><span> Manage Reporting Periods</span></a>
                    </li>
                  
                    <li class="nav-item"><a class="nav-link {% if url_name == 'managefocusarea' %}active{% endif %}" href=" {% url 'portaldata:managefocusarea' %}">
                      <i class="bi bi-menu-button-wide"></i><span> Manage Focus Areas</span></a>
                    </li>
                
                    <li class="nav-item"><a class="nav-link {% if url_name == 'manageindicators' %}active{% endif %}" href=" {% url 'portaldata:manageindicators' %}">
                      <i class="bi bi-menu-button-wide"></i><span> Manage Indicators</span></a>
                    </li>
                    <li class="nav-item"><a class="nav-link {% if url_name == 'indicator-assignment' %}active{% endif %}" href=" {% url 'portaldata:indicator-assignment' %}">
                      <i class="bi bi-menu-button-wide"></i><span> Assign Indicators</span></a>
                    </li>
                    
                    <li class="nav-item"><a class="nav-link {% if url_name == 'managegeneralindicators' %}active{% endif %}" href=" {% url 'portaldata:managegeneralindicators' %}">
                      <i class="bi bi-menu-button-wide"></i><span> Manage General Indicators</span></a>
                    </li>

             

                <!--End Manage Menu-->

                    <li class="nav-heading"></li>
                    
                    <li class="nav-item"><a class="nav-link {% if url_name == 'validate-indicator-data' %}active{% endif %}" href=" {% url 'portaldata:validate-indicator-data' %}">
                      <i class="bi bi-menu-button-wide"></i><span> Manage Data (Validate)</span></a>
                    </li>
                    <li class="nav-item"><a class="nav-link {% if url_name == 'publish-data' %}active{% endif %}" href=" {% url 'portaldata:publish-data' %}">
                      <i class="bi bi-menu-button-wide"></i><span> Publish Data </span></a>
                    </li>


                    <li class="nav-heading"></li>


                    <li class="nav-item"><a class="nav-link {% if url_name == 'dataentrybysadc' %}active{% endif %}" href=" {% url 'portaldata:dataentrybysadc' %}">
                      <i class="bi bi-journal-text"></i><span> Data Entry - SADC</span></a>
                    </li>
                    <li class="nav-heading"></li>

                    <li class="nav-item"><a class="nav-link {% if url_name == 'send-message-admin' %}active{% endif %}" href="{% url 'portaldata:send-message-admin' %}  ">
                      <i class="fas fa-envelope"></i><span> Send Message</span></a>
                    </li>
                    {% endif %}
                    {%endif%}

                  
                 
                   

                    {% if user.is_authenticated and user.is_memberstate %}  
                    <li class="nav-heading"></li>
                    <li class="nav-item"><a class="nav-link {% if url_name == 'dataentrybyms' %}active{% endif %}" href=" {% url 'portaldata:dataentrybyms' %}">
                      <i class="bi bi-journal-text"></i><span> Data Entry</span></a>
                    </li>

                    <li class="nav-item"><a class="nav-link {% if url_name == 'view-indicator-data' %}active{% endif %}" href=" {% url 'portaldata:view-indicator-data' %} ">
                      <i class="fas fa-table"></i><span> View | Export Data ({% reporting_year %})  </span></a>
                    </li>
                    <li class="nav-heading"></li>
                    <li class="nav-item"><a class="nav-link {% if url_name == 'send-message-ms' %}active{% endif %}" href="{% url 'portaldata:send-message-ms' %}  ">
                      <i class="fas fa-envelope"></i><span> Send Message</span></a>
                    </li>
                    {% endif %}
                   

                    

                    {% comment %} {% if user.is_authenticated and user. %}  {% endif %} {% endcomment %}

                    {% if user.is_authenticated and user.is_organisation %}  
           

                    <li class="nav-item"><a class="nav-link {% if url_name == 'dataentrybyorg' %}active{% endif %}" href=" {% url 'portaldata:dataentrybyorg' %}">
                      <i class="bi bi-journal-text"></i><span> Data Entry: {{user.getSysUser.user_organisation}}</span></a>
                    </li>
                    {% endif %}

                  
                   
                    

                    <li class="nav-heading"></li>

                    <li class="nav-item"><a class="nav-link {% if url_name == 'generate-report' %}active{% endif %}" href=" {% url 'portal:generate-report' %} ">
                      <i class="fas fa-table"></i><span> Export Data | Report</span></a>
                    </li>

                    <li class="nav-heading"></li>

                  

                    <li class="nav-item"><a class="nav-link {% if url_name == 'profile' %}active{% endif %}" href="{% url 'portaldata:profile' %}  ">
                      <i class="fas  fa-user"></i><span> Profile</span></a>
                    </li>



                    <li class="nav-item"><a class="nav-link {% if url_name == 'documentation' %}active{% endif %}" href="{% url 'portaldata:documentation' %}">
                      <i class="fa fa-book"></i><span> Documentation</span></a>
                    </li>

                   

                    {% if user.is_authenticated and user.is_superuser %}  

                    <li class="nav-item"><a class="nav-link " href="{% url 'admin:index' %}" >
                      <i class="fas bi-gear "></i><span> Admin Page</span></a>
                    </li>

                    {% endif %}

                    <li class="nav-item"><a class="nav-link " href="{% url 'portal:index' %}" >
                      <i class="fas fa-arrow-circle-left"></i><span> Front Page</span></a>
                    </li>
                </ul>
                {% endwith %}
                <!--<div class="text-center d-none d-md-inline"><button class="btn rounded-circle border-0"
                        id="sidebarToggle" type="button"></button></div> -->
            </div>
        </nav>