core/urls.py
from django.urls import path, include, re_path

from core.views import change_password

app_name = 'core'

urlpatterns = [
    path('accounts/change-password/', change_password,
         name='account_change_password'),

]

ictobservatory/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings

from django.conf.urls.static import static
import notifications.urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("select2/", include("django_select2.urls")),
    re_path(
        "^inbox/notifications/", include(notifications.urls,
                                         namespace="notifications")
    ),
    path("", include("portal.urls")),
    path("portaldata/", include("portaldata.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("core.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# settings.MEDIA_URL, document_root=settings.MEDIA_ROOT changed during deployment

portal/urls.py
from django.urls import path

from portal.views.map_views import map_view
from .views.portal_home_views import index, socio_economic, about
from .views.querydata_views import generate_report

app_name = 'portal'

urlpatterns = [
    #'''Home Page'''
    path('', index, name='index'),

    #'''Socio Economic Charts page'''
    path('socio-economic/', socio_economic, name='socio-economic-charts'),


    #'''Query Data page'''
    path('query-data/', generate_report, name='generate-report'),


    #'''About Page'''
    path('about/', about, name='about'),


    path('map/', map_view, name='map'),



]

portal/views.py
from django.conf import settings
from django.contrib.humanize.templatetags.humanize import intcomma

from django_tables2 import RequestConfig

from django.db.models import Max
from statistics import mean
from datetime import datetime
from django_tables2.export.export import TableExport
import django_tables2 as tables

from django.shortcuts import render
from portal.forms import FilterForm, HomePageFilterYear, get_published_years, latest_published_year


from portaldata.models import ExchangeRateData, GeneralIndicatorData, Indicator, IndicatorData, INDICATORDATA_STATUS, MemberState, Chart, ChartConfig, CHART_TYPE, Published, ScoreCard, ScoreCardConfig


from django.shortcuts import render

from .charts import ColumnChart, LineChart, StackedChart, SpiderWebChart, SunBurstChart

from django_pivot.pivot import pivot

color_blue = ['#2C318A']
color_green = ['#02B052']
color_yellow = ['#C49801']
color_lightblue = ['#3A40B8']
color_lightgreen = ['#02CE5E']

color_lightblue_lightgreen = [color_lightblue[0], color_lightgreen[0]]

tricolors = [color_blue[0], color_green[0], color_yellow[0]]
sixcolors = ['#2C318A', '#02B052',  '#C49801',
             '#BFDB38', '#3C84AB',   '#493801']


'''
Global variables used to populate score cards in the home page
'''
# sadc_mobile_penetration = ''

sadc_network_coverage = ''

avg_pop_coverage_3g = ''

avg_internet_penetration = ''

total_population = ''

total_internet_users = ''


def index(request):
    '''
    Main home page
    This view renders all the charts and score cards in the home page
    '''

    form = HomePageFilterYear(request.GET or None)

    year = latest_published_year()

    if request.method == "GET":

        year_filter = request.GET.get('year_filter')
        if year_filter:
            year = year_filter

    charts = [

        chart_telecom_revenue(year),
        chart_ict_contrib_gdp(year),
        chart_telecom_investment(year),


        chart_mobile_penetration_rate(year),
        chart_fixed_telephone_line(year),
        chart_pop_coveredby_mobl_network(year),
        chart_mobl_geog_coverage(year),
        chart_internet_user_penetration(year),


        chart_inter_internet_bandwidth(year),
        chart_inter_internet_bandwidth_per_user(year),
        chart_inter_internet_bandwidth_per_inhabitant(year),



        chart_fixed_telephone_tariffs(year),
        chart_sms_tariff(year),


        chart_existence_of_policy_by_ms(year),
        chart_existing_ict_regulation(year),





        chart_literacy_rate(year),
    ]

    score_cards = {
        'sadc_mobile_penetration': scorecard_sadc_mobile_penetration(year),
        'sadc_network_coverage': sadc_network_coverage,
        'avg_pop_coverage_3g': avg_pop_coverage_3g,
        'avg_internet_penetration': scorecard_avg_internet_penetration(year)}

    context = {
        'form': form,
        'charts': charts,
        'score_cards': score_cards

    }
    return render(request, 'portal/index.html', context=context)


def about(request):

    return render(request, 'portal/about.html')


def socio_economic(request):

    form = HomePageFilterYear(request.GET or None)

    year = latest_published_year()

    if request.method == "GET":
        year_filter = request.GET.get('year_filter')
        if year_filter:
            year = year_filter

    charts = [chart_population(year),
              chart_population_male_female(year),
              chart_gpd_per_capita(year),
              chart_gni_per_capita(year),

              chart_exchange_rate(year),
              ]

    context = {
        'form': form,

        'charts': charts,


    }

    return render(request, 'portal/socio-economic-charts.html', context=context)


def sum_val(data_dict, indicator_label):
    total = 0
    if data_dict:
        if indicator_label in data_dict:
            if data_dict[indicator_label]:
                try:
                    for i in data_dict[indicator_label]:
                        if i != '':
                            total += float(i)

                    return round(total, 2)
                except:
                    return 0
            else:

                return 0
        else:

            return 0

    else:

        return 0


def mean_val(data_dict, indicator_label):
    if data_dict:
        if indicator_label in data_dict:
            if data_dict[indicator_label]:
                try:
                    return round(mean(d for d in data_dict[indicator_label] if d != ''), 2)
                except:
                    return 0
            else:
                return 0
        else:
            return 0
    else:
        return 0


def percentage_per_indicator(result_list):

    if result_list:
        try:
            percent = [mean(k)*100 for k in zip(*result_list)]

            return percent
        except:
            return 0
    else:
        return 0


def perUser(bandwidth, internet_user):
    if internet_user and bandwidth:
        try:
            return round(float(bandwidth) / float(internet_user), 2)
        except:
            return ''
    else:
        return ''


def scorecard_sadc_mobile_penetration(year):
    "This is for the Average SADC Mobile Penetration Scorecard"

    scorecard = ScoreCard.objects.filter(
        scorecard_name='sadc_mobile_penetration').first()

    if scorecard:

        return scorecard_calculation(scorecard, year)
    else:
        return "-"


def scorecard_avg_internet_penetration(year):
    "This is for the Average SADC Internet Penetration Scorecard"

    scorecard = ScoreCard.objects.filter(
        scorecard_name='avg_internet_penetration').first()

    if scorecard:

        return scorecard_calculation(scorecard, year)
    else:
        return "-"


def scorecard_calculation(scorecard, year):
    query_list_num = []
    query_list_denom = []

    query_list = []

    indicators_list = ScoreCardConfig.objects.filter(scorecard=scorecard)

    if indicators_list:

        for item in indicators_list:

            item_option = item.indicator.label

            indicator_data = list(IndicatorData.objects.filter(
                indicator=item.indicator, reporting_year=year).values_list("ind_value_adjusted", flat=True))

            if item.num_denom:
                if item.num_denom == 'num':
                    item_option = "num"
                    query_list_num.append(indicator_data)
                elif item.num_denom == 'denom':
                    item_option = "denom"
                    query_list_denom.append(indicator_data)
                else:
                    # item_option = "other"
                    query_list.append(indicator_data)
            else:
                query_list.append(indicator_data)

    query_list_num = (query_list_num[0]
                      if query_list_num else query_list_num)
    query_list_denom = (
        query_list_denom[0] if query_list_denom else query_list_denom)

    num = 0
    denom = 0

    if len(query_list_num) == len(query_list_denom):

        for i in range(len(query_list_num)):
            if query_list_num[i] and query_list_denom[i]:

                try:
                    num += float(query_list_num[i])
                    denom += float(query_list_denom[i])
                except:
                    pass
    else:
        if query_list_num:
            if any(isinstance(el, list) for el in query_list_num):
                ls = [item for sublist in query_list_num for item in sublist]

                for item in ls:
                    try:
                        num += float(item)
                    except:
                        pass
            else:
                for item in query_list_num:
                    try:
                        num += float(item)
                    except:
                        pass

        if query_list_denom:
            if any(isinstance(el, list) for el in query_list_denom):
                ls = [item for sublist in query_list_denom for item in sublist]

                for item in ls:
                    try:
                        denom += float(item)
                    except:
                        pass
            else:
                for item in query_list_denom:
                    try:
                        denom += float(item)
                    except:
                        pass

    try:
        return (num/denom)*100
    except:
        return "-"

    # return True


def chart_population(year):
    ''' This is for Population Chart'''

    categories = []

    query_list = []

    indicator_label = ''

    chart_title = ''
    y_axis_title = ''
    aggregation = ''

    data_dict = {}

    chart = Chart.objects.filter(chart_name='chart_population').first()

    if chart:
        chart_title = chart.chart_title
        y_axis_title = chart.y_axis_title
        aggregation = chart.aggregation

        indicators_list = ChartConfig.objects.filter(chart=chart)

        if indicators_list:

            for item in indicators_list:

                indicator_data = IndicatorData.objects.filter(
                    indicator=item.indicator, reporting_year=year)

                query_list.append(indicator_data)

    for qs in query_list:
        data = []
        for entry in qs:

            if entry.member_state.member_state_short_name:
                categories.append(entry.member_state.member_state_short_name)
            else:
                categories.append(entry.member_state.member_state)

            chart_indicator = ChartConfig.objects.filter(
                indicator=entry.indicator).first()

            indicator_label = chart_indicator.series_name if chart_indicator and chart_indicator.series_name else entry.indicator.label

            if (entry.ind_value_adjusted):
                data.append(float(entry.ind_value_adjusted))
            else:
                data.append(entry.ind_value_adjusted)

        data_dict[indicator_label] = data

    if aggregation:

portal/views/map_views.py
from django.http import HttpRequest, HttpResponse
import requests
import json
from django.shortcuts import render
from core.sharedfunctions import get_current_reporting_year
from portaldata.models import INDICATORDATA_STATUS, Indicator, IndicatorData

from django.db.models import F, Q, When
from django.http import JsonResponse


def get_validated_data(indicator, reporting_year):
    '''Takes indicator and year and returns submitted and validated data for the year by indicator'''
    data = list(IndicatorData.objects.filter(
        indicator=indicator, reporting_year='2022',
        # submitted=True, validation_status=INDICATORDATA_STATUS.validated
    ).values(code=F('member_state__member_state_iso3_code'),
             name=F('member_state__member_state'),
             shortname=F('member_state__member_state_short_name'),
             value=F('ind_value_adjusted'),
             ind_name=F('indicator__label')))

    return JsonResponse(data, safe=False)


def split(a, n):
    k, m = divmod(len(a), n)

    d = list(a[i*k+min(i, m):(i+1)*k+min(i+1, m)] for i in range(n))

    return d


def is_number(s):
    try:
        complex(s)  # for int, long, float and complex
    except ValueError:
        return False

    return True


# def split(lst, n):
#     k, m = divmod(len(lst), n)
#     # print(k)
#     for i in range(n):
#         print((i+1)*k+min(i+1, m))
#         lst[i*k+min(i, m):(i+1)*k+min(i+1, m)]

#     return lst

def setOptions():
    '''
    Set general options
    A function to set general options for charts
    '''

    return '''Highcharts.setOptions({
                     lang: {

                        thousandsSep: ','
                        }
                        }
                    );'''


def map_view(request):

    context = {'map': map()}
    return render(request, 'portal/generate-maps.html', context=context)


def map():

    indicator = Indicator.objects.filter(id=1).first()

    data = json.loads(get_validated_data(indicator=indicator,
                                         reporting_year=get_current_reporting_year()).content)

    res = [(float(sub['value']) if is_number(sub['value']) else sub['value'])
           for sub in data]
    #res = [sub['value'] for sub in data]

    res = sorted(res, key=lambda e: (e != '', e))
    #res = sorted(res, key=lambda e: (e is not None, e))

    x = split(res, 4)

    # one = (x[0][-1])
    # two = (x[1][-1])
    # three = (x[2][-1])

    one = (round(x[0][-1]) if is_number(x[0][-1]) else (x[0][-1]))

    two = (round(x[1][-1]) if is_number(x[1][-1]) else (x[1][-1]))
    three = (round(x[2][-1]) if is_number(x[2][-1]) else (x[2][-1]))

    dataclass = []

    if one == '':
        dataclass = []
        dataclass.append({'to': two})
        dataclass.append({'from': two, 'to': three})
        dataclass.append({'from': three})

    if two == '':
        dataclass = []
        dataclass.append({'to': three})

        dataclass.append({'from': three})

    if three == '':
        dataclass = []
        dataclass.append({'from': three})

    # print(one)
    # one = 1
    # two = 2
    # three = 3
    # four = round(x[3][-1])

    # print(x[0][5])

    # print([x])

    topology = requests.get(
        'https://code.highcharts.com/mapdata/custom/africa.topo.json').json()

    # begin = '''
    # (async () => {

    # var md = await fetch(
    #     'https://code.highcharts.com/mapdata/custom/africa.topo.json'
    # ).then(response => response.json());

    # '''

    begin = '{'

    # Instantiate the map
    # Highcharts.mapChart('container',
    map = {

        'chart': {
            # 'map': 'geojson',
            # 'renderTo': 'container',
            # 'height': '60%',
            'spacing': [20, 0, 0, 0],
            # 'plotBorderWidth': 0,
            # 'plotBackgroundColor': '#ffffff',



        },
        # type: ignore
        'title': {'text': indicator.label, 'align': 'center', },

        # 'subtitle': {
        #     'text': 'Demo of drawing all areas in the map, only highlighting partial data',
        #     'align': 'center'
        # },
        'exporting': {
            'sourceWidth': 600,
            'sourceHeight': 500
        },

        'legend': {
            'enabled': 'true',
            'layout': 'vertical',
            'borderWidth': 0,
            'backgroundColor': 'rgba(255,255,255,0.85)',
            'floating': 'true',
            'verticalAlign': 'bottom',
            'align': 'left',
            # 'y': 25
        },
        'credits': {'enabled': 'false'},


        'colorAxis': {
            'dataClasses': dataclass if dataclass else [
                {'to': one},
                {
                    'from': one,
                    'to': two
                },
                {
                    'from': two,
                    'to': three
                },
                {
                    'from': three
                }],

        },


        'mapNavigation': {
            'enabled': 'true',
            'buttonOptions': {
                'align': 'right'
            }
        },

        'mapView': {
            'projection': {
                'name': 'WebMercator'
            },
            'center': [22, -15],
            'zoom': 3.5
        },

        'series': [{
            # 'mapData': 'Highcharts.maps[custom/africa]',
            'mapData': topology,
            # 'type': 'map',
            'animation': {'duration': 1000},
            'name': indicator.label,
            'data': data,

            'joinBy': ['iso-a3', 'code'],
            'nullColor': 'red',

            # 'allAreas': 'true',
            # 'dataLabels': {
            #     'enabled': 'true',
            #     'color': '#FFFFFF',
            #     # 'format': '{point.shortname}',
            #     # 'format': '{point.name}',
            #     'nullFormat': ''
            # },
            # 'tooltip': {
            #     'headerFormat': '',
            #     'pointFormat': '{point.name}: {point.value}'
            # }
        }]
    }

   # end = ';})();'
    end = ';}'

    html = f'''
   <div id="container" >
    <script>
{setOptions()}
    {begin}
    Highcharts.mapChart('container', {map}){end}

    </script>
     </div>

    '''

    return html

portal/templates/portal/index.html
{% extends 'base_portal.html' %} 
{% load dataentrytags %}

{% load static %} 

{% block title %}Home {% endblock title %} 

{% block extra_js_top %}

<script src="{% static 'js/highcharts.src.js' %}"></script>
<script src="{% static 'js/no-data-to-display.js' %}"></script>
<script src="{% static 'js/highcharts-more.js' %}"></script>
<script src="{% static 'js/variable-pie.js' %}"></script>
<script src="{% static 'js/exporting.js' %}"></script>
<script src="{% static 'js/offline-exporting.js' %}"></script>
<script src="{% static 'js/export-data.js' %}"></script>



{% comment %} <script src="https://code.highcharts.com/highcharts.src.js"></script>
<script src="https://code.highcharts.com/modules/no-data-to-display.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://code.highcharts.com/modules/variable-pie.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/offline-exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script> {% endcomment %}

{% endblock extra_js_top %}

   


{% block content %}





  <div id="content">
    <div class="container-fluid">
      <div class="d-sm-flex justify-content-between align-items-center mb-4">
        <h3 class="text-dark mb-0">Dashboard</h3>

        
      
            <div class="col-sm-9 text-end" >
        <a  class="btn btn-primary btn-sm  d-sm-inline-block" role="button"   href="{% url 'portal:generate-report' %}">
            <i class="fas fa-download fa-sm text-white-50"></i>&nbsp;Query Data</a>

            <a  class="btn btn-primary btn-sm  d-sm-inline-block" role="button"   href="{% url 'portal:socio-economic-charts' %}">
                <i class="fas fa-chart-bar fa-sm text-white-50"></i>&nbsp;Socio-Economic Charts</a>
        </div>

       


      </div>

    <div class="row d-block  ">
       
      <form class="row g-3 mb-3" method="GET" >
            <div class="d-inline-flex mt-2  ">

                <div class="">
                    <label for="inputEmail3" class="pt-2 me-3">Year: </label>
                </div>
                <div class="col-sm-2" >
                    {{form.year_filter|addclass:'form-select'}}
                </div>
               
                <input  class="btn btn-primary btn-sm   d-sm-inline-block ms-3" role="button" type="submit" value="Show" >
            <i class="fas fa-fa-undo fa-sm text-white-50"></i></input>
              
            </div>

        </form>
   
    </div>


      <div class="row">
        <div class="col-md-6 col-xl-3 mb-4">
            <div class="card shadow border-start-primary py-2">
                <div class="card-body">
                    <div class="row align-items-center no-gutters">
                        <div class="col me-1">
                            <div class="text-uppercase text-primary fw-bold text-xs mb-1"><span>Average SADC MOBILE PENETRATION&nbsp; &nbsp;&nbsp;</span></div>
                            <div class="text-dark fw-bold h5 mb-0"><span>
                                {% if score_cards.sadc_mobile_penetration == "-" or score_cards.sadc_mobile_penetration == 0  %} - 
                                {% else %}
                                {{score_cards.sadc_mobile_penetration|floatformat}}%
                                {% endif %}
                                </span></div>
                        </div>
                        {% comment %} <div class="col-auto"><i class="fas fa-calendar fa-2x text-gray-300"></i></div> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-xl-3 mb-4">
            <div class="card shadow border-start-success py-2" >
                <div class="card-body">
                    <div class="row align-items-center no-gutters">
                        <div class="col me-1">
                            <div class="text-uppercase text-success fw-bold text-xs mb-1"><span>Average SADC INTERNET PENETRATION</span></div>
                            <div class="text-dark fw-bold h5 mb-0"><span>
                                {% if score_cards.avg_internet_penetration == "-" or score_cards.avg_internet_penetration == 0 %} - 
                                {% else %}
                                {{score_cards.avg_internet_penetration|floatformat}}%
                                {% endif %}
                                </span></div>
                        </div>
                       
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-xl-3 mb-4">
            <div class="card shadow border-start-info ">
                <div class="card-body">
                    <div class="row align-items-center no-gutters">
                        <div class="col me-1">
                            <div class="text-uppercase text-info fw-bold text-xs mb-1"><span>AVG SADC MOBILE NETWORK Geographical COVERAGE</span></div>
                            <div class="row g-0 align-items-center">
                                <div class="col-auto">
                                    <div class="text-dark fw-bold h5 mb-0 me-3"><span>
                                        {% if score_cards.sadc_network_coverage == "-" or  score_cards.sadc_network_coverage == 0 %} - 
                                        {% else %}
                                        {{score_cards.sadc_network_coverage|floatformat}}%
                                        {% endif %}
                                        </span></div>
                                </div>
                                {% comment %} <div class="col">
                                    <div class="progress progress-sm">
                                        <div class="progress-bar bg-info" aria-valuenow="{{score_cards.sadc_network_coverage}}" aria-valuemin="0" aria-valuemax="100" style="width: {{score_cards.sadc_network_coverage}}%;"><span class="visually-hidden">50%</span></div>
                                    </div>
                                </div> {% endcomment %}
                            </div>
                        </div>
                        {% comment %} <div class="col-auto"><i class="fas fa-wifi fa-2x text-gray-300"></i></div> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-xl-3 mb-4">
            <div class="card shadow border-start-warning ">
                <div class="card-body" >
                    <div class="row align-items-center no-gutters">
                        <div class="col me-1">
                            <div class="text-uppercase text-primary fw-bold text-xs mb-1"><span>AVG SADC % Population Coverage by at least 3G</span></div>
                            <div class="text-dark fw-bold h5 mb-0"><span>
                                {% if score_cards.avg_pop_coverage_3g == "-" %} - 
                                {% else %}
                                {{score_cards.avg_pop_coverage_3g|floatformat}}%
                                {% endif %}
                                </span></div>
                        </div>
                        {% comment %} <div class="col-auto"><i class="fas fa-wifi fa-2x text-gray-300"></i></div> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">

    <!--Start: Iterate Charts-->  
    
    {% for chart in charts  %}
       
    <div class="col-lg-4 col-xl-6">
        <div class="card shadow mb-4">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h6 class="text-primary fw-bold m-0">{{chart|slice:"1:2"|first}}   ({{chart|slice:"2:3"|first}})</h6>
                <div class="dropdown no-arrow">
                  
                    <!--Chart Description-->
                    {% if chart|slice:"3:4"|first  %}
                    <button class="btn btn-circle bg-hover-info" data-toggle="popover" 
                    title="{{chart|slice:"1:2"|first}}" 
                    data-bs-content="{{chart|slice:"3:4"|first|safe}}">
                        <span  style="color: blue;" class=" bi bi-info-circle small "></span>
                    </button>
                    {% endif %}
                <!--end-->



                    <button class="btn btn-link btn-sm dropdown-toggle" aria-expanded="false" data-bs-toggle="dropdown" type="button"><i class="fas fa-bars text-bold "></i></button>
                    <div class="dropdown-menu shadow dropdown-menu-end animated--fade-in">
                        <p class="dropdown-header fw-bold">Options:</p>
                            <button class="dropdown-item" onclick="return exportChart({{chart|last}},'viewinfullscreen')" value="viewinfullscreen">View in fullscreen</button>
                            <button class="dropdown-item" onclick="return exportChart({{chart|last}},'png')" value="image/png">Download PNG</button>
                            <button class="dropdown-item" onclick="return exportChart({{chart|last}},'jpeg')" value="image/jpeg">Download JPEG</button>
                            <button class="dropdown-item" onclick="return exportChart({{chart|last}},'pdf')" value="application/pdf">Download PDF</button>
                            <div class="dropdown-divider"></div>
                            <button class="dropdown-item" onclick="return exportChart({{chart|last}},'csv')" value="application/pdf">Download CSV</button>
                            <button class="dropdown-item" onclick="return exportChart({{chart|last}},'xls')" value="application/pdf">Download XLS</button>
                            <button class="dropdown-item" onclick="return exportChart({{chart|last}},'dt')" value="application/pdf">View Data Table</button>
                    </div>
                </div>
            </div>
            <div class="card-body" >
                    {{chart|first|safe}}
           
            </div>
        </div>
    </div>
    {% endfor %}

<!--End: Iterate Charts--> 

<div class="alert alert-success  fade show" role="alert">
    <h4 class="alert-heading">Socio-Economic Charts</h4>
    <p>For socio-economic charts including Population, Population Percentages by Male and Female, GDP per Capita, GNI per Capita and Exchange Rate values, follow the link below.</p><hr>
    <p class="mb-0"><a href=" {% url 'portal:socio-economic-charts' %} "> Socio-Economic Charts.</a></p> 
 

</div>

    

    </div>
      
    </div>
  </div>
  
  
  <script>
    $(function () {
        $('[data-toggle="popover"]').popover()
      }); 

     
    </script>

{% endblock content %}

{% block footer %}<footer class="bg-white sticky-footer">
    <div class="container my-auto">
      <div class="text-center my-auto copyright">
        <span>Copyright © SADC {% now "Y" %}</span>
      </div>
    </div>
  </footer>{% endblock footer %}

{% block extra_js %}
    <script>
        function exportChart(container, option) {
            var chart = $(container).highcharts();

            switch(option) {
                case "print":
                    chart.print();
                    break;
                case "viewinfullscreen":
                    chart.fullscreen.toggle()
                    break;
                case "png":
                    
                    chart.exportChart();
                    break;
                case "jpeg":
                    chart.exportChart({type: 'image/jpeg'});
                    break;
                case "pdf":
                    chart.exportChart({
                        type: 'application/pdf'
                    });
                    break;
                case "csv":
                    chart.downloadCSV();
                    break;
                case "xls":
                    chart.downloadXLS();
                    break;
                case "dt":
                    chart.toggleDataTable()
                    break;
            }
        };  


    {% comment %} document.querySelector(".dropdown-item").addEventListener('click', (event) => {
        alert("here")
        let value = event.target.value;
        alert(value)
    }); {% endcomment %}


    </script>

{% endblock extra_js %}