core/urls.py
from django.urls import path, include, re_path

from core.views import change_password

app_name = 'core'

urlpatterns = [
    path('accounts/change-password/', change_password,
         name='account_change_password'),

]

ictobservatory/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings

from django.conf.urls.static import static
import notifications.urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("select2/", include("django_select2.urls")),
    re_path(
        "^inbox/notifications/", include(notifications.urls,
                                         namespace="notifications")
    ),
    path("", include("portal.urls")),
    path("portaldata/", include("portaldata.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("core.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# settings.MEDIA_URL, document_root=settings.MEDIA_ROOT changed during deployment

portaldata/urls.py
from django.urls import path

from portaldata.views.profile_views import view_profile
from .views.home_views import documentation, index, send_message_by_admins, send_message_by_ms
from .views.admin_views import (
    GeneralIndicatorCreateView,
    GeneralIndicatorListView,
    GeneralIndicatorUpdateView,
    IndicatorCreateView,
    IndicatorListtableView,
    IndicatorUpdateView,
    FocusAreaListView,
    FocusAreaCreateView,
    FocusAreaUpdateView,
    ReportingPeriodCreateView,
    ReportingPeriodListView,
    ReportingPeriodUpdateView,
    indicator_list_view,
    manage_indicatorassignment,
    publish_data,
)

from .views.indicator_data_views import (
    ViewIndicatorDatatableView,
    data_entry_progress_by_ms,
    manage_general_indicatordata,
    manage_indicatordata,
    manage_indicatordata_organisation,
    show_indicator_definition,
    submit_indicator_data_by_ms,
    data_entry_progress_by_org,
    submit_indicator_data_by_org,
    view_indicatordata,
)

from .views.exchangerate_data_views import exchange_rate_data

from .views.indicator_data_validation import (
    IndicatorDatatableView,
    indicatordata_list_view,
    validate_data,
    send_back_for_revision,
)


app_name = "portaldata"

urlpatterns = [
    path("", index, name="index"),
    path("create-indicator/", IndicatorCreateView.as_view(), name="createindicator"),
    #'''Page to show the list of indicators to be validated'''
    path("manage-indicators/", indicator_list_view, name="manageindicators"),
    #''' Ajax page to feed data to the page described above'''
    path(
        "manage-indicator-ajax/",
        IndicatorListtableView.as_view(),
        name="manage-indicator-ajax",
    ),
    path(
        "update-indicator/<int:pk>/",
        IndicatorUpdateView.as_view(),
        name="updateindicator",
    ),
    path("manage-focus-area/", FocusAreaListView.as_view(), name="managefocusarea"),
    path("create-focus-area/", FocusAreaCreateView.as_view(), name="createfocusarea"),
    path(
        "update-focus-area/<int:pk>/",
        FocusAreaUpdateView.as_view(),
        name="updatefocusarea",
    ),
    path(
        "manage-reporting-period/",
        ReportingPeriodListView.as_view(),
        name="managereportingperiod",
    ),
    path(
        "create-reporting-period/",
        ReportingPeriodCreateView.as_view(),
        name="createreportingperiod",
    ),
    path(
        "update-reporting-period/<int:pk>/",
        ReportingPeriodUpdateView.as_view(),
        name="updatereportingperiod",
    ),
    path(
        "indicator-assignment/", manage_indicatorassignment, name="indicator-assignment"
    ),
    path(
        "manage-general-indicator/",
        GeneralIndicatorListView.as_view(),
        name="managegeneralindicators",
    ),
    path(
        "create-general-indicator/",
        GeneralIndicatorCreateView.as_view(),
        name="creategeneralindicator",
    ),
    path(
        "update-general-indicator/<int:pk>/",
        GeneralIndicatorUpdateView.as_view(),
        name="updategeneralindicator",
    ),
    # '''Data Entry Progress Page URL for Member States'''
    path("data-entry-by-ms/", data_entry_progress_by_ms, name="dataentrybyms"),
    # '''Data Entry Progress for Organisations'''
    path("data-entry-by-org/", data_entry_progress_by_org, name="dataentrybyorg"),
    # Data Entry Page for SADC - For General Indicators
    path(
        "manage-general-indicator-data/",
        manage_general_indicatordata,
        name="dataentrybysadc",
    ),
    # '''Data Entry Page for Member States - For a selected Focus Area'''
    path(
        "manage-indicator-data/<int:id>/",
        manage_indicatordata,
        name="manage_indicatordata",
    ),
    # '''Data Entry Page for Organizations - for a selected indicator'''
    path(
        "manage-indicator-data-org/<int:id>/",
        manage_indicatordata_organisation,
        name="manage_indicatordata_organisation",
    ),
    # '''Page to show the list of indicators data completed by Member States'''
    path(
        "view-indicator-data/",
        view_indicatordata,
        name="view-indicator-data",
    ),
    # '''Ajax page to feed data to the page described above'''
    path(
        "view-indicator-data-ajax/",
        ViewIndicatorDatatableView.as_view(),
        name="view-indicator-data-ajax",
    ),
    # '''Exchange data entry page for Member States'''
    path("dataentrybyms/exchange-rate", exchange_rate_data, name="exchange-rate"),
    path("show-definition/<int:id>/",
         show_indicator_definition, name="showdefinition"),
    # '''Indicator Submit Page (for Submit button) for Member States'''
    path("submit-indicator-data/", submit_indicator_data_by_ms,
         name="submitIndicatorData"),
    # '''Indicator Submit Page for Organizations'''
    path(
        "submit-indicator-data-by-org/",
        submit_indicator_data_by_org,
        name="submitIndicatorDatabyOrg",
    ),
    # '''Start indicator Validation'''
    # '''Page to show the list of indicators to be validated'''
    path(
        "validate-indicator-data/",
        indicatordata_list_view,
        name="validate-indicator-data",
    ),
    # '''Ajax page to feed data to the page described above'''
    path(
        "manage-indicator-data-ajax/",
        IndicatorDatatableView.as_view(),
        name="manage-indicator-data-ajax",
    ),
    # '''Validate data button'''
    path("validate-data/", validate_data, name="validate-data"),
    # '''Send back to revision button'''
    path("sendback/<int:id>/", send_back_for_revision, name="sendback"),
    # '''End indicator validation'''
    # '''Profile'''
    path("manage-profile/", view_profile, name="profile"),
    # '''Documentation'''
    path("documentation/", documentation, name="documentation"),
    # '''Send Message for Admins'''
    path("send-message-admin/", send_message_by_admins, name="send-message-admin"),
    # '''Send Message for Member States'''
    path("send-message-ms/", send_message_by_ms, name="send-message-ms"),
    # '''Publish'''
    path("publish-data/", publish_data, name="publish-data"),
]

portaldata/models.py
from django.template.defaultfilters import linebreaksbr
from django.contrib import admin
from django.core.cache import cache
from django.db.models.constraints import UniqueConstraint
from django.core.exceptions import NON_FIELD_ERRORS
from django.db.models.signals import post_save
from email.policy import default
import imp
from operator import truediv
from random import choices
from tabnanny import verbose
from django.utils.html import html_safe, format_html

# from unittest.util import _MAX_LENGTH
from django.db import models
from django.db.models import Count, Q
import json
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
import datetime
from collections import namedtuple
from django.dispatch import receiver
from django.utils.text import slugify
import random
import string
from django.utils.safestring import SafeText, mark_safe
from django.contrib.humanize.templatetags.humanize import intcomma
from django.utils.translation import gettext_lazy as _

from core.sharedfunctions import get_current_reporting_year


DATA_TYPE = namedtuple(
    "DATA_TYPE",
    "currency number decimal percentage text select text_area url email date",
)._make(range(10))

IND_ASSIGNED_TO = namedtuple(
    "IND_ASSIGNED_TO", "MEMBER_STATES ORGANIZATIONS SADC"
)._make(["M", "O", "S"])


INDICATORDATA_STATUS = namedtuple("STATUS", "draft ready returned validated")._make(
    range(1, 5)
)

CHART_TYPE = namedtuple(
    "CHART_TYPE", "column line stacked stacked100pct spiderweb sunburst"
)._make(range(6))


# def generate_unique_slug(klass, field, id, identifier='slug'):
#     """
#     generate unique slug.
#     """

#     origin_slug = slugify(field)
#     unique_slug = origin_slug
#     numb = 1
#     mapping = {
#         identifier: unique_slug,
#     }
#     obj = klass.objects.filter(**mapping).first()
#     while obj:
#         if obj.id == id:
#             break
#         rnd_string = random.choices(
#             string.ascii_lowercase, k=(len(unique_slug)))
#         unique_slug = '%s-%s-%d' % (origin_slug,
#                                     ''.join(rnd_string[:10]), numb)
#         mapping[identifier] = SafeText(unique_slug)
#         numb += 1
#         obj = klass.objects.filter(**mapping).first()
#     return unique_slug


class FocusArea(models.Model):

    """Focus Area Model"""

    FOCUSAREA_STATUS_CHOICES = [(True, "Active"), (False, "Inactive")]

    sn = models.IntegerField(verbose_name="S/N", unique=True, blank=True)
    title = models.CharField(verbose_name="Focus Area", max_length=255)
    abbreviation = models.CharField(max_length=50, unique=True)
    description = models.TextField(blank=True)

    focusarea_status = models.BooleanField(
        choices=FOCUSAREA_STATUS_CHOICES,
        default=True,
    )
    created_date = models.DateTimeField(
        auto_now_add=True)  # only during the creation

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="Focus_Area_Created_By",
        on_delete=models.DO_NOTHING,
    )
    last_update = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="Focus_Area_Updated_By",
        on_delete=models.DO_NOTHING,
    )

    def __str__(self):
        return self.title

    def count_core_indicators(self):
        ind_count = (
            Indicator.objects.filter(focus_area=self)
            .filter(indicator_type="Core")
            .count()
        )
        return ind_count

    def count_extended_indicators(self):
        ind_count = (
            Indicator.objects.filter(focus_area=self)
            .filter(indicator_type="Extended")
            .count()
        )
        return ind_count

    def count_active_indicators(self):
        ind_count = (
            Indicator.objects.filter(focus_area=self).filter(
                status="Active").count()
        )
        return ind_count

    def count_archived_indicators(self):
        ind_count = (
            Indicator.objects.filter(focus_area=self).filter(
                status="Archived").count()
        )
        return ind_count

    def count_required_indicators(self):
        ind_count = (
            Indicator.objects.filter(focus_area=self).filter(
                required=True).count()
        )
        return ind_count

    def count_active_required_indicators(self):
        ind_count = (
            Indicator.objects.filter(focus_area=self, required=True)
            .filter(status="Active")
            .count()
        )
        return ind_count

    def count_optional_indicators(self):
        ind_count = (
            Indicator.objects.filter(focus_area=self).filter(
                required=False).count()
        )
        return ind_count

    def count_active_required_indicators_by_assignment(self, assignedto):
        ind_count = (
            Indicator.objects.filter(
                focus_area__focusarea_status=True,
                focus_area=self,
                required=True,
                indicator_assigned_to=assignedto,
            )
            .filter(status="Active")
            .count()
        )
        return ind_count

    def count_completed_indicators_by_assignment(
        self, assignedto, memberstate, reporting_year
    ):
        ind_count = (
            IndicatorData.objects.filter(
                indicator__focus_area=self,
                indicator__focus_area__focusarea_status=True,
                indicator__indicator_assigned_to=assignedto,
                member_state=memberstate,
                reporting_year=reporting_year,
            )
            .exclude(value_NA=False, ind_value__exact="")
            .exclude(value_NA=False, ind_value__isnull=True)
            .exclude(indicator__required=False)
            .count()
        )
        return ind_count

    def check_submitted(self, assignedto, memberstate, reporting_year):
        ind_count = IndicatorData.objects.filter(
            indicator__focus_area=self,
            indicator__indicator_assigned_to=assignedto,
            reporting_year=reporting_year,
            member_state=memberstate,
            submitted=False,
        ).count()

        return ind_count

    def get_revision_request(self, assignedto, memberstate, reporting_year):
        ind_count = IndicatorData.objects.filter(
            indicator__focus_area=self,
            indicator__indicator_assigned_to=assignedto,
            reporting_year=reporting_year,
            member_state=memberstate,
            submitted=False,
            validation_status=INDICATORDATA_STATUS.returned,
        ).count()

        return ind_count

    def count_indicators(self):
        ind_count = (
            Indicator.objects.filter(focus_area=self)
            .exclude(indicator_assigned_to=IND_ASSIGNED_TO.ORGANIZATIONS)
            .exclude(indicator_assigned_to=IND_ASSIGNED_TO.SADC)
            .count()
        )
        return ind_count

    def next_sn(self):
        """Return Serial Number for a new indicator (count + 1)"""
        next_sn = FocusArea.objects.count() + 1
        return next_sn

    class Meta:
        ordering = ["sn"]
        verbose_name_plural = "Focus Areas"

        verbose_name = "Focus Area"


class MemberState(models.Model):

    """Model for Member States"""

    MEMBERSTATE_STATUS_CHOICES = [(True, "Active"), (False, "Inactive")]

    member_state = models.CharField(
        max_length=255, unique=True, verbose_name="Member State"
    )
    member_state_short_name = models.CharField(
        max_length=30, blank=True, verbose_name="Short Name"
    )

    member_state_iso3_code = models.CharField(
        max_length=3, verbose_name="ISO 3 Code", blank=True
    )

    memberstate_status = models.BooleanField(
        choices=MEMBERSTATE_STATUS_CHOICES, default=True, verbose_name="Status"
    )

    @property
    def ms_shortname(self):
        if self.member_state_short_name:
            return self.member_state_short_name
        else:

            return self.member_state

    def count_active(self):
        active_member_states = MemberState.objects.filter(
            memberstate_status=True
        ).count()
        return active_member_states

    def __str__(self):
        return self.member_state

    class Meta:
        ordering = ["member_state"]
        verbose_name_plural = "Member States"


class Indicator(models.Model):

    """Model for Indicators"""

    DATA_TYPE = [
        (DATA_TYPE.currency, "Currency"),
        (DATA_TYPE.number, "Whole Number"),
        (DATA_TYPE.decimal, "Decimal"),
        (DATA_TYPE.percentage, "Percentage"),
        (DATA_TYPE.text, "Text"),
        (DATA_TYPE.select, "Select (Yes/No)"),
        (DATA_TYPE.text_area, "Text Area"),
        (DATA_TYPE.url, "URL"),
        (DATA_TYPE.email, "Email"),
        (DATA_TYPE.date, "Date"),
    ]

    INDICATOR_TYPE_CHOICES = [
        ("Core", "Core"),
        ("Extended", "Extended"),
    ]

    INDICATOR_STATUS_CHOICES = [("Active", "Active"), ("Archived", "Archived")]

    CURRENCY_TYPE_CHOICES = [("usd", "USD"), ("local", "Local Currency")]

    INDICATOR_ASSIGNED_TO_GROUPS = [
        (IND_ASSIGNED_TO.MEMBER_STATES, "Member States"),
        (IND_ASSIGNED_TO.ORGANIZATIONS, "Organisations"),
        (IND_ASSIGNED_TO.SADC, "SADC"),
    ]

    YESNO_CHOICES = [(True, "Yes"), (False, "No")]

    focus_area = models.ForeignKey(
        FocusArea, on_delete=models.PROTECT, verbose_name="Focus Area"
    )

    indicator_number = models.CharField(
        max_length=50, unique=True, verbose_name="Indicator Number"
    )

    label = models.CharField(
        "Indicator", max_length=255, help_text="Enter the indicator here"
    )

    data_type = models.PositiveSmallIntegerField(
        choices=DATA_TYPE, verbose_name="Data Type"
    )

    choices = models.TextField(
        blank=True,

portaldata/views/profile_views.py
from django.shortcuts import render, redirect

from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required
def view_profile(request):
    '''Show User's Profile on the Profile page'''

    user = request.user
    context = {'user': user}

    if request.method == 'POST':
        first_name = request.POST['firstname']

        last_name = request.POST['lastname']
        phone = request.POST['phone']

        user.first_name = first_name
        user.last_name = last_name
        user.phone = phone

        user.save()

    return render(request, 'portaldata/profile.html', context=context)

portaldata/templates/portaldata/_definition.html
{% load static %}

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content text-start">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Definition </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        
        <div class="modal-body justify-content-end text-justify ">
          <div class="modal-title fw-bold">{{ indicator.label }}</div>
         
          {{ indicator.definition }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          
        </div>
      </div>
    </div>
  </div>

portaldata/templates/portaldata/focusarea_form.html
{% extends 'base_auth.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Focus Area Management{% endblock title %}

{% block content %}

{% include 'partials/_sidebar.html' %}



<div class="d-flex flex-column" id="content-wrapper">
    <div id="content">

     {% include 'partials/_auth_navbar.html' %}


        <div class="container-fluid">

            <h5 class="text-dark mb-4 fw-bold">{{form.initial.pagetitle}} Focus Area</h5>

            

            <div class="card shadow">
               
                <div class="card-body mt-4">

                    <form  method="post">
                        {% csrf_token %}
                      

                       
                        {% crispy form %}     
                    

                   

                    <button id="btncancel" type="button" class="btn btn-dark float-end "  >
                        <a class="text-decoration-none text-white"  href="{% url 'portaldata:managefocusarea' %}">Close</a></button>
                    <button id="save" type="submit" class="btn btn-primary  float-end me-4">Save</button>
                

                    </form>

                </div>

           

        </div>

    </div>

</div>

{% endblock content %}

{% block extra_js %}

<script src="{% static 'js/confirmExit.js' %}"></script>

{% endblock extra_js %}

portaldata/templates/portaldata/generalindicator_list.html
{% extends 'base_auth.html' %}
{% load static %}

{% block title %}General Indicators Management{% endblock title %}

{% block content %}

{% include 'partials/_sidebar.html' %}





<div class="d-flex flex-column" id="content-wrapper">
    <div id="content">

     {% include 'partials/_auth_navbar.html' %}


        <div class="container-fluid">

          <div class="card shadow">
            <div class="card-header py-3">
                 <h4 class="text-end text-primary m-0 fw-bold">Manage General Indicators</h4>
                 <div class="col-md-4 d-sm-flex justify-content-end    ">
                  <a href="{% url 'portaldata:creategeneralindicator' %}" class="btn btn-primary me-3  ">
                    <span class="fa fa-plus-circle" aria-hidden="true"> </span>  Add New
                  </a>
    
                 
                </div>
                 {% comment %} <p class="text-end text-primary m-0 fw-bold" style="border-color: var(--bs-green);">Year: <span style="color: rgb(78, 223, 84);">{{reporting_year}}</span></p> {% endcomment %}
            </div>
          
            <!--begin::Page Title-->
            <div class="card-body">
         
       

        
      <div class="table-responsive">
        <table class="table table-responsive table-hover">
          <thead class="table-light  borderit">
            {% comment %} <th>S/N</th> {% endcomment %}
            <th>Indicator</th>
            <th>Definition</th>
           
            <th>Edit</th>

          </thead>

       {% for genind in GeneralIndicators  %}
        <tbody>

            {% comment %} <td>{{focusarea.sn}}</td> {% endcomment %}
            <td>{{genind.indicator_label}}</td>
            <td>{{genind.definition}}</td>
            
            <td> <a href="{% url 'portaldata:updategeneralindicator' pk=genind.pk %}" class="btn btn-primary btn-esm me-3  ">
                <span class="fa fa-pencil-alt" aria-hidden="true"> </span>
              </a></td>
          
            {% endfor %}
        </tbody>

      </table>
    </div>
    </div>

        </div>

    </div>

</div>



{% endblock content %}

portaldata/templates/portaldata/indicator_form.html
{% extends 'base_auth.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Indicator Management{% endblock title %}



{% block content %}

{% include 'partials/_sidebar.html' %}



<div class="d-flex flex-column" id="content-wrapper">
    <div id="content">

     {% include 'partials/_auth_navbar.html' %}


        <div class="container-fluid">
            <h5 class="text-dark mb-4 fw-bold">{{form.initial.title}} Indicator</h5>
            {% comment %} <div class="col-md-8 d-sm-flex justify-content-between align-items-center ">
              
               
                <h4 class="text-dark mb-0  fw-boldest">Add Indicator</h4>
             
            </div> {% endcomment %}
            <div class="card shadow">
               
                <div class="card-body mt-4">
             <form  method="post">
                {% csrf_token %}
              
                {% comment %} <label for="ind" id="ind_num" value="{{form.next_indicator_num}}">test</label> {% endcomment %}

                <input hidden type="text" name="label" maxlength="255" required="" value="{{form.next_indicator_num}}" id="ind_num">
       
                
                
            
               
                {% crispy form %}  
          

            <button id="btncancel" type="button" class="btn btn-dark float-end "  >
                <a class="text-decoration-none text-white"  href="{% url 'portaldata:manageindicators' %}">Close</a></button>
            <button id="save" type="submit" class="btn btn-primary  float-end me-4">Save</button>

           

            </form>

        </div>

        </div>

    </div>

</div>

{% endblock content %}




{% block extra_js %}

<script src="{% static 'js/confirmExit.js' %}"></script>

    <script>
        var focusareaVal = document.getElementById('id_focus_area').value;

        var choicesVal = document.getElementById('id_data_type').value;

        var next_indicator = document.getElementById('ind_num').value;

        var elChoice = document.querySelector("#id_choices");

        var elabel = findLableForControl(elChoice);

        //var currencyType = document.querySelector('#id_type_of_currency');
        //var currencyTypeLabel = findLableForControl(currencyType);
        
        var t = document.getElementById('id_indicator_number').value

     
        
        var dictionary = JSON.parse(next_indicator);
        console.log(dictionary);

        toggleFocusAreas(focusareaVal);
        document.getElementById('id_focus_area').addEventListener('change', function() {
            console.log('You selected: ', this.value);
            toggleFocusAreas(this.value);
            
          });

          if(t){
            document.getElementById('id_indicator_number').value=t
        }

        
  

        toggleChoices(choicesVal);

        document.getElementById('id_data_type').addEventListener('change', function() {
          console.log('You selected: ', this.value);
          toggleChoices(this.value);
        });

        function toggleChoices(value) {

        
          if (value == 5  ) {
            elChoice.hidden = false;
            elabel.hidden=false; 

            //currencyTypeLabel.hidden = true;
            //currencyType.hidden = true;
          }

        /*if (value == 0){
            elChoice.hidden = true;
            elabel.hidden=true;

            currencyTypeLabel.hidden = false;
            currencyType.hidden = false;

        }*/

                      
       else {
           
            elChoice.hidden = true;
            elabel.hidden=true;
           // currencyTypeLabel.hidden = true;
           // currencyType.hidden = true;
            
        }
        




      }

      function toggleFocusAreas(value) {

        //var t=document.getElementById('id_indicator_number').value
        //if(t) 
        //{
        //alert(t)
        //document.getElementById('id_indicator_number').value = t
           // }
        //else if (typeof dictionary[value] === 'undefined')
        //{
            
         //       alert(t.value)
        //}
       // else{
      //      document.getElementById('id_indicator_number').value = dictionary[value]
      //  }
        
        
       // console.log(dictionary[value])
        //console.log(typeof(document.getElementById('id_indicator_number').value)
        //alert(typeof(t.value))
//        console.log(value)
        if (typeof dictionary[value] === 'undefined') {
            //console.log("underined")
        }
        else if (typeof((document.getElementById('id_indicator_number').value)) != 'undefined') {
            //console.log("here inside")
            document.getElementById('id_indicator_number').value = dictionary[value]
            
        }
        else {
            //console.log("last")
            document.getElementById('id_indicator_number').value = dictionary[value]
            
        }
    } 
      function findLableForControl(el) {
        var idVal = el.id;
        labels = document.getElementsByTagName('label');
        for( var i = 0; i < labels.length; i++ ) {
           if (labels[i].htmlFor == idVal)
                return labels[i];
        }
     }
    </script>
{% endblock extra_js %}

portaldata/templates/portaldata/reportingperiod_list.html
{% extends 'base_auth.html' %}
{% load static %}

{% block title %}Reporting Period Management{% endblock title %}

{% block content %}

{% include 'partials/_sidebar.html' %}



<div class="d-flex flex-column" id="content-wrapper">
    <div id="content">

     {% include 'partials/_auth_navbar.html' %}


        <div class="container-fluid">

            <div class="card shadow">
                <div class="card-header py-3">
                     <h4 class="text-end text-primary m-0 fw-bold">Manage Reporting Periods</h4>
                     <div class="col-md-4 d-sm-flex justify-content-end    ">
                        <a href="{% url 'portaldata:createreportingperiod' %}" class="btn btn-primary me-3  ">
                            <span class="fa fa-plus-circle" aria-hidden="true"> </span>  Add New
                        </a>
    
                        {% comment %} <a href="{% url 'portaldata:index' %}" class="btn btn-primary">
                            <span class="fa fa-file-export" aria-hidden="true"> </span>  Export List
                        </a> {% endcomment %}
                    </div>
                     {% comment %} <p class="text-end text-primary m-0 fw-bold" style="border-color: var(--bs-green);">Year: <span style="color: rgb(78, 223, 84);">{{reporting_year}}</span></p> {% endcomment %}
                </div>

                <!--Data table-->
                <div class="card-body">



            <!--begin::Page Title and search-->
            
           

            {% comment %} <div class="row-cols-auto justify-content-end mb-4 ">
                
                <div class="form-group col-4 float-end mb-2">
                    <input type="text" placeholder="Search" id="searchField" class="form-control">
    
                </div>
            </div> {% endcomment %}

             <!--end::Page Title and Search-->

             <!--Begin:List-->
             <div class="table-responsive">
             <table class="table table-responsive table-hover">
                <thead class="table-light  borderit">
                  <th>Reporting Start Date</th>
                  <th>Reporting End Date</th>
                  <th>Status</th>
                  
                  <th>Edit</th>
      
                </thead>

             {% for reportingperiod in ReportingPeriods  %}
            
             <tbody>
                {% comment %} <td>{{focusarea.sn}}</td>
                <td>{{focusarea.title}}</td>
                <td>{{focusarea.get_focusarea_status_display}}</td> {% endcomment %}
                <td >{{reportingperiod.reporting_start_date}}</td>
                <td >{{reportingperiod.reporting_end_date}}</td>

                <td >
                    {% if reportingperiod.current %}
                    <span class="badge bg-success">&nbsp;&nbsp;&nbsp;Current&nbsp;&nbsp;&nbsp;&nbsp;</span>
                    {% endif %}
                   </td>
                
                <td> <a href="{% url 'portaldata:updatereportingperiod' pk=reportingperiod.pk %}" class="btn btn-primary btn-esm me-3  ">
                    <span class="fa fa-pencil-alt" aria-hidden="true"> </span>
                  </a></td> 
                {% comment %} S/N:
                Title:
                Total:
                Core:
                Extended:
                Active:
                Acrchived:
                Required:
                Optional: {% endcomment %}
                {% endfor %}
             </tbody>
                
               

               
              
            

             <!--End:List-->

        </table>
    </div>
    </div>
    </div>
<div>
{% endblock content %}