core/urls.py
from django.urls import path, include, re_path

from core.views import change_password

app_name = 'core'

urlpatterns = [
    path('accounts/change-password/', change_password,
         name='account_change_password'),

]

ictobservatory/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings

from django.conf.urls.static import static
import notifications.urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("select2/", include("django_select2.urls")),
    re_path(
        "^inbox/notifications/", include(notifications.urls,
                                         namespace="notifications")
    ),
    path("", include("portal.urls")),
    path("portaldata/", include("portaldata.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("core.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# settings.MEDIA_URL, document_root=settings.MEDIA_ROOT changed during deployment

portal/urls.py
from django.urls import path

from portal.views.map_views import map_view
from .views.portal_home_views import index, socio_economic, about
from .views.querydata_views import generate_report

app_name = 'portal'

urlpatterns = [
    #'''Home Page'''
    path('', index, name='index'),

    #'''Socio Economic Charts page'''
    path('socio-economic/', socio_economic, name='socio-economic-charts'),


    #'''Query Data page'''
    path('query-data/', generate_report, name='generate-report'),


    #'''About Page'''
    path('about/', about, name='about'),


    path('map/', map_view, name='map'),



]

portaldata/urls.py
from django.urls import path

from portaldata.views.profile_views import view_profile
from .views.home_views import documentation, index, send_message_by_admins, send_message_by_ms
from .views.admin_views import (
    GeneralIndicatorCreateView,
    GeneralIndicatorListView,
    GeneralIndicatorUpdateView,
    IndicatorCreateView,
    IndicatorListtableView,
    IndicatorUpdateView,
    FocusAreaListView,
    FocusAreaCreateView,
    FocusAreaUpdateView,
    ReportingPeriodCreateView,
    ReportingPeriodListView,
    ReportingPeriodUpdateView,
    indicator_list_view,
    manage_indicatorassignment,
    publish_data,
)

from .views.indicator_data_views import (
    ViewIndicatorDatatableView,
    data_entry_progress_by_ms,
    manage_general_indicatordata,
    manage_indicatordata,
    manage_indicatordata_organisation,
    show_indicator_definition,
    submit_indicator_data_by_ms,
    data_entry_progress_by_org,
    submit_indicator_data_by_org,
    view_indicatordata,
)

from .views.exchangerate_data_views import exchange_rate_data

from .views.indicator_data_validation import (
    IndicatorDatatableView,
    indicatordata_list_view,
    validate_data,
    send_back_for_revision,
)


app_name = "portaldata"

urlpatterns = [
    path("", index, name="index"),
    path("create-indicator/", IndicatorCreateView.as_view(), name="createindicator"),
    #'''Page to show the list of indicators to be validated'''
    path("manage-indicators/", indicator_list_view, name="manageindicators"),
    #''' Ajax page to feed data to the page described above'''
    path(
        "manage-indicator-ajax/",
        IndicatorListtableView.as_view(),
        name="manage-indicator-ajax",
    ),
    path(
        "update-indicator/<int:pk>/",
        IndicatorUpdateView.as_view(),
        name="updateindicator",
    ),
    path("manage-focus-area/", FocusAreaListView.as_view(), name="managefocusarea"),
    path("create-focus-area/", FocusAreaCreateView.as_view(), name="createfocusarea"),
    path(
        "update-focus-area/<int:pk>/",
        FocusAreaUpdateView.as_view(),
        name="updatefocusarea",
    ),
    path(
        "manage-reporting-period/",
        ReportingPeriodListView.as_view(),
        name="managereportingperiod",
    ),
    path(
        "create-reporting-period/",
        ReportingPeriodCreateView.as_view(),
        name="createreportingperiod",
    ),
    path(
        "update-reporting-period/<int:pk>/",
        ReportingPeriodUpdateView.as_view(),
        name="updatereportingperiod",
    ),
    path(
        "indicator-assignment/", manage_indicatorassignment, name="indicator-assignment"
    ),
    path(
        "manage-general-indicator/",
        GeneralIndicatorListView.as_view(),
        name="managegeneralindicators",
    ),
    path(
        "create-general-indicator/",
        GeneralIndicatorCreateView.as_view(),
        name="creategeneralindicator",
    ),
    path(
        "update-general-indicator/<int:pk>/",
        GeneralIndicatorUpdateView.as_view(),
        name="updategeneralindicator",
    ),
    # '''Data Entry Progress Page URL for Member States'''
    path("data-entry-by-ms/", data_entry_progress_by_ms, name="dataentrybyms"),
    # '''Data Entry Progress for Organisations'''
    path("data-entry-by-org/", data_entry_progress_by_org, name="dataentrybyorg"),
    # Data Entry Page for SADC - For General Indicators
    path(
        "manage-general-indicator-data/",
        manage_general_indicatordata,
        name="dataentrybysadc",
    ),
    # '''Data Entry Page for Member States - For a selected Focus Area'''
    path(
        "manage-indicator-data/<int:id>/",
        manage_indicatordata,
        name="manage_indicatordata",
    ),
    # '''Data Entry Page for Organizations - for a selected indicator'''
    path(
        "manage-indicator-data-org/<int:id>/",
        manage_indicatordata_organisation,
        name="manage_indicatordata_organisation",
    ),
    # '''Page to show the list of indicators data completed by Member States'''
    path(
        "view-indicator-data/",
        view_indicatordata,
        name="view-indicator-data",
    ),
    # '''Ajax page to feed data to the page described above'''
    path(
        "view-indicator-data-ajax/",
        ViewIndicatorDatatableView.as_view(),
        name="view-indicator-data-ajax",
    ),
    # '''Exchange data entry page for Member States'''
    path("dataentrybyms/exchange-rate", exchange_rate_data, name="exchange-rate"),
    path("show-definition/<int:id>/",
         show_indicator_definition, name="showdefinition"),
    # '''Indicator Submit Page (for Submit button) for Member States'''
    path("submit-indicator-data/", submit_indicator_data_by_ms,
         name="submitIndicatorData"),
    # '''Indicator Submit Page for Organizations'''
    path(
        "submit-indicator-data-by-org/",
        submit_indicator_data_by_org,
        name="submitIndicatorDatabyOrg",
    ),
    # '''Start indicator Validation'''
    # '''Page to show the list of indicators to be validated'''
    path(
        "validate-indicator-data/",
        indicatordata_list_view,
        name="validate-indicator-data",
    ),
    # '''Ajax page to feed data to the page described above'''
    path(
        "manage-indicator-data-ajax/",
        IndicatorDatatableView.as_view(),
        name="manage-indicator-data-ajax",
    ),
    # '''Validate data button'''
    path("validate-data/", validate_data, name="validate-data"),
    # '''Send back to revision button'''
    path("sendback/<int:id>/", send_back_for_revision, name="sendback"),
    # '''End indicator validation'''
    # '''Profile'''
    path("manage-profile/", view_profile, name="profile"),
    # '''Documentation'''
    path("documentation/", documentation, name="documentation"),
    # '''Send Message for Admins'''
    path("send-message-admin/", send_message_by_admins, name="send-message-admin"),
    # '''Send Message for Member States'''
    path("send-message-ms/", send_message_by_ms, name="send-message-ms"),
    # '''Publish'''
    path("publish-data/", publish_data, name="publish-data"),
]

templates/base_auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} - SADC ICT Observatory</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'fonts/fontawesome-all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'fonts/bootstrap-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    

    {% comment %} <link href="{% static 'ajax_datatable/css/style.css' %}" rel="stylesheet" />
    <link href="{% static 'css/jquery.dataTables.min.css' %}" rel="stylesheet" /> {% endcomment %}

    {% block extracss %}{% endblock extracss %}
    
    
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png" />

   
    {% comment %} <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> {% endcomment %}
    
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    

    {% block extrajstop %}{% endblock extrajstop %}

    

    {% comment %} <script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
    <script src="{% static 'ajax_datatable/js/utils.js' %}"></script>
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script> {% endcomment %}


    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&amp;display=swap">



</head>

<body id="page-top">
  
    <div id="wrapper">

      {% block content %}

        {% comment %} <!--begin::Sidebar -->
        {% block sidebar %}{% endblock sidebar %}
        
        <!--end::Sidebar --> {% endcomment %}

        

        {% endblock content %}
        
        
        
        <a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
    {% comment %} <script src="{% static 'js/bootstrap.min.js' %}"></script> {% endcomment %}
    {% comment %} <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script> {% endcomment %}
    {% comment %} <script src="{% static 'js/chart.min.js' %}"></script> {% endcomment %}
    <script src="{% static 'js/bs-init.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


   
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script> {% endcomment %}
{% comment %} <script>
    $(document).ready(function(){
      {% block js_scripts %}{% endblock %}
    });
  </script>   {% endcomment %}
  <script src="{% static 'js/theme.js' %}"></script>

  {% block extra_js %}{% endblock extra_js %}
    

</body>

</html>

templates/base_portal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="SADC ICT Observatory is a central point of reference for reliable, accurate and up-to-date collection and dissemination of ICT indicators, measurement, benchmarking and reports"/>

    <title>{% block title %}{% endblock title %} - SADC ICT Observatory</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
   
    <link
      rel="stylesheet"
      href="{% static 'fonts/fontawesome-all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
    <link rel="stylesheet" href="{% static 'css/highcharts.css' %}" />
     <!-- Chart.JS -->
     {% comment %} <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3"></script> {% endcomment %}
    
    {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'fonts/bootstrap-icons.css' %}" />
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png" />
    <!--<script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>-->
   
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    {% comment %} <script
        src="https://code.jquery.com/jquery-3.5.1.min.js" >
    </script> {% endcomment %}

    {% comment %} <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script src="https://code.highcharts.com/modules/no-data-to-display.js"></script>
    <script src="https://code.highcharts.com/highcharts-more.js"></script>
    <script src="https://code.highcharts.com/modules/variable-pie.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/offline-exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script> {% endcomment %}
    

  

    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&amp;display=swap" />
  
      
     {% block extra_style %}{% endblock extra_style %} 
     {% block extra_js_top %}{% endblock extra_js_top %}
    </head>

  <body id="page-top">
    <!--Start::navbar-->

    <nav  id="sadc-brand" class="navbar navbar-light navbar-expand-md py-3 sadc-brand">
      <div class="container-fluid">
        <a
          class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0"
          href="{% url 'portal:index' %}">
          <div class="logo">
            <img src="{% static 'img/sadc-logo-circle.svg' %}  " alt="logo" />
          </div>
          <div class="p-2 text-decoration-none d-none d-sm-block">
            <span> SADC ICT Observatory </span>
          </div>
        </a>

        <button
          data-bs-toggle="collapse"
          class="navbar-toggler"
          data-bs-target="#navcol-2">
          <span class="visually-hidden">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navcol-2">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'portal:index' %}">Home</a>
            </li>
            <li class="nav-item"><a class="nav-link" href="{% url 'portal:about' %}">About</a></li>
            <li class="nav-item"><a class="nav-link" href="https://www.sadc.int/">SADC website</a></li>

            {% if user.is_authenticated %}
           
            <li class="nav-item dropdown no-arrow">
              <li class="nav-item">
                <a class=" nav-link" 
                href="{% url 'portaldata:index' %}"><i
                class="fas fa-arrow-circle-right mt-1 text-sm"></i> Backend</a></li>
          
              <div class="nav-item dropdown no-arrow"><a class="dropdown-toggle nav-link"
                      aria-expanded="false" data-bs-toggle="dropdown"  href="#">
                      <span  class=" d-lg-inline me-2 text-gray-600 small">Welcome: {{ user.get_full_name|title }}</span>
                  <div class="dropdown-menu shadow dropdown-menu-end animated--grow-in"><a
                          class="dropdown-item" href="{% url 'portaldata:index' %}"><i
                              class="fas fa-user fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Backend</a>
                              
                      <div class="dropdown-divider"></div><a class="dropdown-item" href="{% url 'logout' %}"><i
                              class="fas fa-sign-out-alt fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Logout</a>
                  </div>
              </div>
            </li>
            
             {% else %}
            {% comment %} ?next={{ request.path }} {% endcomment %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Sign In</a></li>  
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <!--End::navbar-->

    <div id="wrapper">
      <div class="d-flex flex-column px-lg-5 pt-5" id="content-wrapper">
      {% block content %}{% endblock content %}
      </div>
      <a class="border rounded d-inline scroll-to-top" href="#page-top"
        ><i class="fas fa-angle-up"></i
      ></a>
    </div>

    {% block footer %}{% endblock footer %}

 

    

    

    {% comment %} <script src="{% static 'js/bootstrap.min.js' %}"></script> {% endcomment %}
    {% comment %} <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script> {% endcomment %}
    {% comment %} <script
        src="http://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous">
    </script> {% endcomment %}
   <script 
        src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" 
        crossorigin="anonymous">
    </script>
    <script 
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" 
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" 
        crossorigin="anonymous">
    </script> 

   

    

    {% comment %} <!-- Chart.JS -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3"></script>

    
    <script src="{% static 'js/chart.min.js' %}"></script> {% endcomment %}
    <script src="{% static 'js/bs-init.js' %}"></script>
    <script src="{% static 'js/theme.js' %}"></script>

    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
     {% endcomment %}
    {% block extra_js %}

    
    {% endblock extra_js %}
     {% comment %} <script>
      $(document).ready(function(){
        {% block js_scripts %}{% endblock %}
      })
    </script>  {% endcomment %}
  </body>
</html>